# 공통 설정
spring:
  jpa:
    show-sql: false
    open-in-view: false
    database-platform: MYSQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.default_fetch_size: ${chunkSize:100}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:100}
      hibernate.order_inserts: true
      hibernate.order_updates: true
---
#local
spring:
  config:
    activate:
      on-profile: 'db-local'
  jpa:
    show-sql: true
    database-platform: MYSQL
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: study
    password: Wjdals0217!
    url: jdbc:mysql://localhost:3306/MAPLOG?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
---
# dev

---
# prod